
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myadmin
      MONGO_INITDB_ROOT_PASSWORD: mysecurepassword
    volumes:
      - mongodb_data:/data/db

  backend:
    image: sahilsharma603/money-lens-backend:${VERSION}
    container_name: my_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      MONGO_URI:"mongodb://myadmin:mysecurepassword@mongodb:27017/mydatabase"
      JWT_SECRET:"3eea8e9f7d546b7de6480b7c5bde527073e8d7cfb25a6a7433bb762b7f9e5368708f6c15c9f674f5d002e37f8d8edce2b0ddc4e9cf7df0fa13adad6b3826440e"
      WEBHOOK_URL:"https://6323-206-45-4-68.ngrok-free.app/api/plaid/webhook"
     

    depends_on:
      - mongodb

  frontend:
    image: sahilsharma603/money-lens-frontend:${VERSION}
    container_name: my_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    command: ["npm", "start"]

volumes:
  mongodb_data:
