name: CD Pipeline - Build, Push, and Deploy Locally

on:
  push:
    branches:
      - final_CD_deployment 
  pull_request:
    branches:
      - final_CD_deployment 
  workflow_dispatch:
    inputs:
      version:
        description: 'Money-lens version (if empty, defaults to sprint3)'
        required: false
        default: 'sprint3'

jobs:
  build-and-deploy:
    # This job uses a self-hosted runner which should have Docker and Docker Compose installed.
    runs-on: self-hosted
    env:
      # Use provided version input or default to 'sprint3'
      VERSION: ${{ github.event.inputs.version || 'sprint3' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the backend image
      - name: Build and Push Backend Image
        working-directory: ./backend
        run: |
          docker build -t sahilsharma603/money-lens-backend:${{ env.VERSION }} .
          docker push sahilsharma603/money-lens-backend:${{ env.VERSION }}

      # Build and push the frontend image
      - name: Build and Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t sahilsharma603/money-lens-frontend:${{ env.VERSION }} .
          docker push sahilsharma603/money-lens-frontend:${{ env.VERSION }}

      # Deploy locally using Docker Compose
      - name: Deploy Locally
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d
